disabled_rules:
# Default Rules에서 비활성화할 규칙
- identifier_name
- type_name
- line_length
- trailing_whitespace
- force_cast
- nesting
- function_parameter_count
- function_body_length
- cyclomatic_complexity
- legacy_constructor
- inclusive_language
- file_length
- private_over_fileprivate
opt_in_rules:
# 기본적으로는 비활성화 되어있지만 활성화하고 싶은 규칙
- empty_count # .count==0 보다는 .isEmpty를 사용하는 것이 좋습니다.
- empty_string # 빈 String 문자열과 비교하는 것 보다는 .isEmpty를 사용하는 것이 좋습니다.
excluded:
# 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
- Pods
- Universe-iOS/Sources/AppDelegate.swift
- Universe-iOS/Sources/SceneDelegate.swift
