# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Universe-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Universe-iOS
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'Then'
  pod 'SwiftLint'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'MobileVLCKit', '~>3.3.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  
end
