name: Universe-iOS PR Checker

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '.github/workflows/PRchecker.yml'
      - 'Universe-iOS/.swiftlint.yml'
      - 'Universe-iOS/**/*.swift'
      
jobs:
  SwiftLint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
        run: swiftlint --config Universe-iOS/.swiftlint.yml
